[build]
  publish = "_site"
  command = "bundle exec npx tinacms build -c \"jekyll build\""

[functions]
  directory = "netlify/functions"

[context.production.environment]
  BUNDLE_PATH = "vendor/bundle"